version: '3.7'
x-app: &app
  # image: ruby:2.6.3
  build: .
  volumes:
  - .:/app
  - bundle:/usr/local/bundle
  - node_modules:/app/node_modules
  depends_on:
  - postgres
services:
  app:
    <<: *app
    command: ['rails', 's', '-b', '0.0.0.0', '-p', '5010']
    ports:
    - 5010:5010
    tmpfs:
    - /app/tmp/pids
  spring:
    <<: *app
    command: ['bin/spring', 'server']
  postgres:
    image: postgres:11.3-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
  socket-proxy:
    image: hiroshi3110/socket-proxy
    ports:
    - 3100:3100
volumes:
  bundle:
  node_modules:
  pgdata:
