version: '3.7'
services:
  app:
    # image: ruby:2.6.3
    build: .
    command: ['rails', 's', '-b', '0.0.0.0', '-p', '5010']
    working_dir: /app
    ports:
    - 5010:5010
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules

volumes:
  bundle:
  node_modules:
