version: '3.7'
x-app: &app
  # image: ruby:2.6.3
  build: .
  environment:
  - SOCKET_PROXY_URL=http://sp.async.lvh.me:3200/
  - POSTGRES_HOST=postgres
  - WEBPACKER_DEV_SERVER_HOST=webpacker
  tmpfs:
  - /app/tmp/pids
  volumes:
  - .:/app
  - bundle:/usr/local/bundle
  - node_modules:/app/node_modules
  - yarn_cache:/usr/local/share/.cache/yarn/v4
services:
  app:
    <<: *app
    command: ['rails', 's', '-b', '0.0.0.0', '-p', '5010']
    ports:
    - 5010:5010
    networks:
      default:
        aliases:
        - async.lvh.me
    depends_on:
    - postgres
    - socket-proxy
    - webpacker
  webpacker:
    <<: *app
    command: ['bin/webpack-dev-server']
    ports:
      - 3035:3035
  spring:
    <<: *app
    command: ['bin/spring', 'server']
    ports:
    - 5020:5020
  postgres:
    image: postgres:11.3-alpine
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
  socket-proxy:
    image: hiroshi3110/socket-proxy:0.1.0
    environment:
    - PORT=3200
    ports:
    - 3200:3200
    networks:
      default:
        aliases:
        - sp.async.lvh.me
volumes:
  bundle:
  node_modules:
  pgdata:
  yarn_cache:
